version: '3.3'

services:
  colorvote-server:
    build: ./backend
    restart: always
    volumes:
      - ./backend/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
      - "traefik.http.services.sentry.loadbalancer.server.port=3002"
      - "traefik.http.routers.sentry.rule=Host(`api.colorvote.ch`)"
      - "traefik.http.routers.sentry.entrypoints=web"
      - "traefik.http.routers.sentry.middlewares=https_redirect"
      - "traefik.http.routers.sentry_secured.rule=Host(`api.colorvote.ch`)"
      - "traefik.http.routers.sentry_secured.entrypoints=websecure"
      - "traefik.http.routers.sentry_secured.tls=true"
      - "traefik.http.routers.sentry_secured.tls.certresolver=myresolver"
    networks:
      - web
networks:
  web:
    external: true
